-- 1. Words Table (The Dictionary)
create table public.words (
  id bigint generated by default as identity primary key,
  word text unique not null,
  syllables int default 0,
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Words
alter table public.words enable row level security;

-- Policy: Everyone can read words
create policy "Public words are viewable by everyone"
  on public.words for select
  using ( true );

-- Policy: Everyone can insert (crowdsourcing) - Optional, maybe restrict to logged in?
-- For now, let's allow it for the "auto-add" feature
create policy "Anyone can insert words"
  on public.words for insert
  with check ( true );
  
-- Policy: Update likes (We need a function for this ideally to prevent abuse, but RLS works too)
create policy "Anyone can update likes"
  on public.words for update
  using ( true );

-- 2. Missing Words Table (Search Analytics)
create table public.missing_words (
  word text primary key,
  attempts int default 1,
  last_searched_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.missing_words enable row level security;

create policy "Anyone can insert/update missing words"
  on public.missing_words for all
  using ( true );

-- 3. Trigger to Auto-Promote Missing Words
-- Logic: If attempts >= 4, move to 'words' table and delete from 'missing_words'
create or replace function promote_missing_word()
returns trigger as $$
begin
  if NEW.attempts >= 4 then
    -- Insert into words if not exists
    insert into public.words (word, syllables)
    values (NEW.word, 0) -- Syllables will be 0 initially
    on conflict (word) do nothing;
    
    -- Delete from missing_words
    delete from public.missing_words where word = NEW.word;
  end if;
  return NEW;
end;
$$ language plpgsql security definer;

create trigger on_missing_word_threshold
  after update on public.missing_words
  for each row
  execute procedure promote_missing_word();

-- 4. User Lyrics Table
create table public.lyrics (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text,
  content text,
  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.lyrics enable row level security;

create policy "Users can CRUD their own lyrics"
  on public.lyrics for all
  using ( auth.uid() = user_id );

-- 5. User Likes (to prevent infinite liking)
create table public.user_likes (
  user_id uuid references auth.users not null,
  word_id bigint references public.words not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, word_id)
);

alter table public.user_likes enable row level security;

create policy "Users can manage their likes"
  on public.user_likes for all
  using ( auth.uid() = user_id );

-- 6. Helper RPC to 'toggle like' securely
create or replace function toggle_like(target_word_id bigint)
returns void as $$
declare
  uid uuid;
begin
  uid := auth.uid();
  
  if exists (select 1 from public.user_likes where user_id = uid and word_id = target_word_id) then
    -- Unlike
    delete from public.user_likes where user_id = uid and word_id = target_word_id;
    update public.words set likes = likes - 1 where id = target_word_id;
  else
    -- Like
    insert into public.user_likes (user_id, word_id) values (uid, target_word_id);
    update public.words set likes = likes + 1 where id = target_word_id;
  end if;
end;
$$ language plpgsql security definer;
